### ISSUE TITLE
libmnl is also required

### ISSUE THREAD

**Issue by blp** [vmware/guest-introspection-nsx#15]
The README notes that most of the libraries required to build.  libmnl also appears to be required:

> blp@sigill:~/nicira/guest-introspection-nsx/src(0)$ make
> ...
> gcc -o /home/blp/nicira/guest-introspection-nsx/src/vmw_conn_notify /home/blp/nicira/guest-introspection-nsx/src/vmw_conn_main.o /home/blp/nicira/guest-introspection-nsx/src/vmw_conn_netfilter.o -L/usr/lib64/ -L/usr/lib/x86_64-linux-gnu/lib -lpthread -lglib-2.0 -lmnl -lnfnetlink -lnetfilter_queue -lnetfilter_conntrack
> /usr/bin/ld: cannot find -lmnl
> collect2: error: ld returned 1 exit status

Running "sudo apt-get install libmnl-dev" solved the problem for me.  Therefore, I recommend updating the README.

**Comment by apunde** [comment]
Thanks for pointing that out. The README is updated.
