### ISSUE TITLE
Version and Protocol handshake

### ISSUE THREAD

**Issue by nawate** [vmware/guest-introspection-nsx#3]
1. Version check at the client side: When a client connects to opensource component
  GI-NSX over Unix local domain socket. Both exchange version and protocol. But it looks like the versions are ignored at both the ends. We are requesting a strict version check at the client side for i.g. Client-A supported Gi-NSX version will be checked if it's not matched and we are going to disconnect. We have added this check because now GI-NSX is getting updated with some other feature request like DNS. This feature packets can't be handled by release client(1.3.2.0). To avoid the problem
we are enabling this strict version check

 2. Protocol check at GI-NSX side: So fare we are asking GI_NSX to give use
  TCP and UDP packets in the protocol. BUT GI-NSX process following kind of
  packets
  - TCP_INBOUND_PRE_CONNECT
  - TCP_OUTBOUD_PRE_CONNECT
  - TCP_CONNECTION_ESTABLISHED
  - TCP_DISCONNECT
  - UDP_PACKETS

  Out of these 5 types of packets IF some clients don't want TCP_CONNECTION_ESTABLISHED
  and TCP_DISCONNECT. Then we are asking GI-NSX to not send these two type of packets. So that we can avoid to-n-fro of packets and reduce some load from GI-NSX side.

**Comment by apunde** [comment]
Fix merged 073e9d7064f1f206756430c392629eda77d9d9b0
